source 'https://rubygems.org'

gem 'sinatra', '1.4.7'
gem 'padrino-helpers', '~> 0.13'
gem 'ficrip', github: 'toroidal-code/ficrip', branch: 'master'
gem 'concurrent-ruby', '~> 1.0.2'
gem 'concurrent-ruby-ext'
gem 'rufus-scheduler', '~> 3.2'
gem 'rake'
gem 'puma'
gem 'rack', '1.5.2'

gem 'haml'
gem 'slim'
gem 'oj'
gem 'oj_mimic_json'
gem 'coffee-script'

gem 'activesupport', '< 5.0.0'
gem 'newrelic_rpm'
